### ISSUE TITLE
issue after upgrade to 5.2

### ISSUE THREAD

**Issue by killmasta93** [sebastian13/zabbix-template-speedtest#2]
Hi Currently updated to 5.2 zabbix and were getting an issue after updating to 5.2 on zabbix server

Thank you 

```
Traceback (most recent call last):
  File "/usr/bin/speedtest-cli", line 2000, in <module>
    main()
  File "/usr/bin/speedtest-cli", line 1986, in main
    shell()
  File "/usr/bin/speedtest-cli", line 1875, in shell
    secure=args.secure
  File "/usr/bin/speedtest-cli", line 1091, in __init__
    self.get_config()
  File "/usr/bin/speedtest-cli", line 1174, in get_config
    map(int, server_config['ignoreids'].split(','))
ValueError: invalid literal for int() with base 10: ''
usage: speedtest-cli [-h] [--no-download] [--no-upload] [--single] [--bytes]
                     [--share] [--simple] [--csv]
                     [--csv-delimiter CSV_DELIMITER] [--csv-header] [--json]
                     [--list] [--server SERVER] [--exclude EXCLUDE]
                     [--mini MINI] [--source SOURCE] [--timeout TIMEOUT]
                     [--secure] [--no-pre-allocate] [--version]
speedtest-cli: error: argument --server: expected one argument
zabbix_sender [24251]: ERROR: [line 1] 'Key value' required
```

**Comment by killmasta93** [comment]
bump?

**Comment by farzadha2** [comment]
same here having the same issue any updates to this?

**Comment by killmasta93** [comment]
seems to be and speed test issue had to update 

https://github.com/sivel/speedtest-cli/pull/771
